# Generated by Django 4.2.5 on 2024-07-18 04:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='profesional',
            options={'verbose_name': 'Profesional', 'verbose_name_plural': 'Profesionales'},
        ),
        migrations.AlterModelOptions(
            name='profesor',
            options={'verbose_name': 'Profesor', 'verbose_name_plural': 'Profesores'},
        ),
    ]
