# Generated by Django 4.2.5 on 2024-07-19 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repositorio', '0002_alter_profesional_options_alter_profesor_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Responsable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=60)),
                ('apellido', models.CharField(max_length=60)),
                ('posicion', models.CharField(max_length=60)),
            ],
        ),
    ]
